name: Terraform Deploy (include Integration Tests)

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      API_HOST:
        description: 'Description of API_HOST'
        required: true
        type: string
  push:
    branches:
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: AWS_DEPLOYMENT

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: 🏗️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: 🚫 Disable Terraform Debug Logs
        run: echo "TF_LOG=ERROR" >> $GITHUB_ENV

      - name: 🔄 Initialize Terraform
        run: terraform init

      - name: 🎨 Check Terraform Format
        run: terraform fmt -check -recursive

      - name: ✅ Validate Terraform Configuration
        run: terraform validate

      - name: 📝 Set Terraform Variables
        run: |
          touch terraform.tfvars
          echo "webapp_ami_id = \"${{ vars.WEBAPP_AMI_ID }}\"" >> terraform.tfvars
          echo "mysql_ami_id = \"${{ vars.MYSQL_AMI_ID }}\"" >> terraform.tfvars
          echo "database_username = \"${{ vars.DATABASE_USERNAME }}\"" >> terraform.tfvars
          echo "database_password = \"${{ secrets.DATABASE_PASSWORD }}\"" >> terraform.tfvars
          echo "webapp_secret_key = \"${{ secrets.WEBAPP_SECRET_KEY }}\"" >> terraform.tfvars
          echo "Terraform Variables Configured ✅"
          cat terraform.tfvars

      - name: 📋 Terraform Plan
        run: terraform plan

      - name: 🚀 Deploy Infrastructure (Terraform Apply)
        run: terraform apply -auto-approve

      - name: 🌍 Get API Server Public IP
        id: get_ip
        run: echo "WEBAPP_IP=$(terraform output -raw webapp_public_ip)" >> $GITHUB_ENV

      - name: 📡 Store API Server Address
        run: echo "API_HOST=${{ env.WEBAPP_IP }}" >> $GITHUB_ENV

      - name: 🔬 Run Integration Tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'Integration Tests'
          inputs: '{"API_HOST": "${{ env.API_HOST }}"}'

      - name: ❌ Destroy Terraform Infrastructure
        if: always() # Ensures destruction runs even if tests fail
        continue-on-error: true # Prevents workflow from failing due to destroy issues
        run: terraform destroy -auto-approve
